-- AlterTable
ALTER TABLE `Property` ADD COLUMN `detailViewCount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `impressionCount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `leadCount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `priorityScore` INTEGER NOT NULL DEFAULT 0;
